In [3]:
#PANDAS:
#ekonomik ve finansal çalışmalar için kullanılır. Bir çok veri yapısıyla çalışma imkanı sağlamaktadır.
#birçok farklı kaynaktan veriyi okuma imkanına sahiptir.

In [4]:
import pandas as pd
import seaborn as sns

In [5]:
#Pandas Series
# Pandas serileri tek boyutlu ve indeks bilgisi barındıran bir veri tipidir.
# Pandas dataframe'i ise çok boyutlu ve indeks bilgisi barındıran bir diğer veri tipidir.

s = pd.Series([10, 77, 12, 4, 5])
type(s)
s.index
s.dtype
s.size
s.ndim
s.values
type(s.values)
s.head(3)
s.tail(2)

3    4
4    5
dtype: int64

In [6]:
#VERİ OKUMA (READİNG DATA)

df = pd.read_csv("/content/sample_data/california_housing_test.csv")
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
0,-122.05,37.37,27.0,3885.0,661.0,1537.0,606.0,6.6085,344700.0
1,-118.30,34.26,43.0,1510.0,310.0,809.0,277.0,3.5990,176500.0
2,-117.81,33.78,27.0,3589.0,507.0,1484.0,495.0,5.7934,270500.0
3,-118.36,33.82,28.0,67.0,15.0,49.0,11.0,6.1359,330000.0
4,-119.67,36.33,19.0,1241.0,244.0,850.0,237.0,2.9375,81700.0

In [7]:
#VERİYE HIZLI BAKIŞ (QUICK LOOK at DATA)
df = sns.load_dataset("titanic")
df.head()
df.tail()
df.shape
df.info()
df.columns
df.index
df.describe().T
df.isnull().values.any()
df.isnull().sum()
df["sex"].head()
df["sex"].value_counts()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

sex
male      577
female    314
Name: count, dtype: int64

In [8]:
#PANDAS'TA SEÇİM İŞLEMLERİ (SELECTION in PANDAS)
df = sns.load_dataset("titanic")
df.head()
df.index
df[0:13]
df.drop(0,axis=0).head()
delete_indexes = [1,3,5,7]
df.drop(delete_indexes,axis=0).head(10)

#DEĞİŞKENİ INDEX'E ÇEVİRMEK
df["age"].head()
df.age.head()

df.index = df["age"]

df.drop("age",axis=1,inplace=True)
df.head()
# INDEX'I DEĞİŞKENE ÇEVİRMEK

df.index
df["age"] = df.index
df.head()
df.drop("age",axis=1,inplace=True)
df.reset_index()
df.head()

,survived,pclass,sex,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
age,,,,,,,,,,,,,,
22.0,0,3,male,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
38.0,1,1,female,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
26.0,1,3,female,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
35.0,1,1,female,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
35.0,0,3,male,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [29]:
# @title Varsayılan başlık metni
#DEĞİŞKENLER ÜZERİNDE İŞLEMLER
pd.set_option("display.max_columns", None)
df = sns.load_dataset("titanic")
df.head()

"age" in df
df["age"].head()
type(df["age"].head())
df.age.head()

df[["age","alive"]]
col_names = ["age","adult_male","alive"]
df[col_names]

df["age2"] = df["age"] ** 2
df["age3"] = df["age"] / df["age2"]
df.drop("age3",axis=1).head()
df.drop(col_names, axis=1).head()

df.loc[:, ~df.columns.str.contains("age")].head()


# iloc & loc

# iloc: integer based selection
df.iloc[0:3]
df.iloc[0,0]

#loc: label based selection
df.loc[0:3]

df.loc[0:3, "age"]

col_names = ["age","embarked","alive"]
df.loc[0:3, col_names]



#KOŞULLU SEÇİM (CONDITIONAL SELECTION)

df[df["age"]>50].head()
df[df["age"]>50]["age"].count()
df.loc[df["age"]>50, ["age", "class"]].head()

df.loc[df["age"]>50, ["age", "class"]].count()

df.loc[(df["age"]>50) & (df["sex"]=="male"), ["age", "class"]].head()

     age   class
6   54.0   First
33  66.0  Second
54  65.0   First
94  59.0   Third
96  71.0   First

In [37]:
#TOPLULAŞTIRMA ve GRUPLAMA (AGGREGATION & GROUPING)
df["age"].mean()
df.groupby("sex")["age"].mean()
df.groupby("sex").agg({"age":["mean","sum"]})
df.groupby("sex").agg({"age":["mean","sum"],
                       "survived":"mean"})
df.groupby(["sex","embark_town"]).agg({"age":["mean","sum"],
                       "survived":"mean"})
df.groupby(["sex","embark_town","class"]).agg({"age":["mean","sum"],
                       "survived":"mean"})
df.groupby(["sex","embark_town","class"]).agg({"age":["mean","sum"],
                       "survived":"mean"}).sort_values(("age","mean"),ascending=False)

df.pivot_table("survived", "sex", ["embarked","class"])
df.pivot_table("survived", "sex", "embarked")

<ipython-input-37-074ff7dd7db0>:9: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["sex","embark_town","class"]).agg({"age":["mean","sum"],
<ipython-input-37-074ff7dd7db0>:11: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.groupby(["sex","embark_town","class"]).agg({"age":["mean","sum"],
<ipython-input-37-074ff7dd7db0>:14: FutureWarning: The default value of observed=False is deprecated and will change to observed=True in a future version of pandas. Specify observed=False to silence this warning and retain the current behavior
  df.pivot_table("survived", "sex", ["embarked","class"])

embarked         C         Q         S
sex
female    0.876712  0.750000  0.689655
male      0.305263  0.073171  0.174603

In [11]:
#APPLY ve LAMBDA

In [12]:
# BİRLEŞTİRME (JOIN) İŞLEMLERİ